// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDoctorEmail holds the string denoting the doctor_email field in the database.
	FieldDoctorEmail = "doctor_email"
	// FieldDoctorName holds the string denoting the doctor_name field in the database.
	FieldDoctorName = "doctor_name"

	// EdgeDoctorID holds the string denoting the doctor_id edge name in mutations.
	EdgeDoctorID = "doctor_id"

	// Table holds the table name of the user in the database.
	Table = "users"
	// DoctorIDTable is the table the holds the doctor_id relation/edge.
	DoctorIDTable = "treatments"
	// DoctorIDInverseTable is the table name for the Treatment entity.
	// It exists in this package in order to avoid circular dependency with the "treatment" package.
	DoctorIDInverseTable = "treatments"
	// DoctorIDColumn is the table column denoting the doctor_id relation/edge.
	DoctorIDColumn = "user_doctor_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldDoctorEmail,
	FieldDoctorName,
}

var (
	// DoctorEmailValidator is a validator for the "doctor_email" field. It is called by the builders before save.
	DoctorEmailValidator func(string) error
	// DoctorNameValidator is a validator for the "doctor_name" field. It is called by the builders before save.
	DoctorNameValidator func(string) error
)
