// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// StatusTracking is the predicate function for statustracking builders.
type StatusTracking func(*sql.Selector)

// Treatment is the predicate function for treatment builders.
type Treatment func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
