// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/Haiserest/app/ent/patient"
	"github.com/Haiserest/app/ent/statustracking"
	"github.com/Haiserest/app/ent/treatment"
	"github.com/Haiserest/app/ent/user"

	"github.com/facebookincubator/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePatient        = "Patient"
	TypeStatusTracking = "StatusTracking"
	TypeTreatment      = "Treatment"
	TypeUser           = "User"
)

// PatientMutation represents an operation that mutate the Patients
// nodes in the graph.
type PatientMutation struct {
	config
	op                Op
	typ               string
	id                *int
	patient_age       *int
	addpatient_age    *int
	patient_name      *string
	clearedFields     map[string]struct{}
	patient_id        map[int]struct{}
	removedpatient_id map[int]struct{}
	done              bool
	oldValue          func(context.Context) (*Patient, error)
}

var _ ent.Mutation = (*PatientMutation)(nil)

// patientOption allows to manage the mutation configuration using functional options.
type patientOption func(*PatientMutation)

// newPatientMutation creates new mutation for $n.Name.
func newPatientMutation(c config, op Op, opts ...patientOption) *PatientMutation {
	m := &PatientMutation{
		config:        c,
		op:            op,
		typ:           TypePatient,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPatientID sets the id field of the mutation.
func withPatientID(id int) patientOption {
	return func(m *PatientMutation) {
		var (
			err   error
			once  sync.Once
			value *Patient
		)
		m.oldValue = func(ctx context.Context) (*Patient, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Patient.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPatient sets the old Patient of the mutation.
func withPatient(node *Patient) patientOption {
	return func(m *PatientMutation) {
		m.oldValue = func(context.Context) (*Patient, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PatientMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PatientMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *PatientMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetPatientAge sets the patient_age field.
func (m *PatientMutation) SetPatientAge(i int) {
	m.patient_age = &i
	m.addpatient_age = nil
}

// PatientAge returns the patient_age value in the mutation.
func (m *PatientMutation) PatientAge() (r int, exists bool) {
	v := m.patient_age
	if v == nil {
		return
	}
	return *v, true
}

// OldPatientAge returns the old patient_age value of the Patient.
// If the Patient object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *PatientMutation) OldPatientAge(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldPatientAge is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldPatientAge requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPatientAge: %w", err)
	}
	return oldValue.PatientAge, nil
}

// AddPatientAge adds i to patient_age.
func (m *PatientMutation) AddPatientAge(i int) {
	if m.addpatient_age != nil {
		*m.addpatient_age += i
	} else {
		m.addpatient_age = &i
	}
}

// AddedPatientAge returns the value that was added to the patient_age field in this mutation.
func (m *PatientMutation) AddedPatientAge() (r int, exists bool) {
	v := m.addpatient_age
	if v == nil {
		return
	}
	return *v, true
}

// ResetPatientAge reset all changes of the "patient_age" field.
func (m *PatientMutation) ResetPatientAge() {
	m.patient_age = nil
	m.addpatient_age = nil
}

// SetPatientName sets the patient_name field.
func (m *PatientMutation) SetPatientName(s string) {
	m.patient_name = &s
}

// PatientName returns the patient_name value in the mutation.
func (m *PatientMutation) PatientName() (r string, exists bool) {
	v := m.patient_name
	if v == nil {
		return
	}
	return *v, true
}

// OldPatientName returns the old patient_name value of the Patient.
// If the Patient object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *PatientMutation) OldPatientName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldPatientName is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldPatientName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPatientName: %w", err)
	}
	return oldValue.PatientName, nil
}

// ResetPatientName reset all changes of the "patient_name" field.
func (m *PatientMutation) ResetPatientName() {
	m.patient_name = nil
}

// AddPatientIDIDs adds the patient_id edge to Treatment by ids.
func (m *PatientMutation) AddPatientIDIDs(ids ...int) {
	if m.patient_id == nil {
		m.patient_id = make(map[int]struct{})
	}
	for i := range ids {
		m.patient_id[ids[i]] = struct{}{}
	}
}

// RemovePatientIDIDs removes the patient_id edge to Treatment by ids.
func (m *PatientMutation) RemovePatientIDIDs(ids ...int) {
	if m.removedpatient_id == nil {
		m.removedpatient_id = make(map[int]struct{})
	}
	for i := range ids {
		m.removedpatient_id[ids[i]] = struct{}{}
	}
}

// RemovedPatientID returns the removed ids of patient_id.
func (m *PatientMutation) RemovedPatientIDIDs() (ids []int) {
	for id := range m.removedpatient_id {
		ids = append(ids, id)
	}
	return
}

// PatientIDIDs returns the patient_id ids in the mutation.
func (m *PatientMutation) PatientIDIDs() (ids []int) {
	for id := range m.patient_id {
		ids = append(ids, id)
	}
	return
}

// ResetPatientID reset all changes of the "patient_id" edge.
func (m *PatientMutation) ResetPatientID() {
	m.patient_id = nil
	m.removedpatient_id = nil
}

// Op returns the operation name.
func (m *PatientMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Patient).
func (m *PatientMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *PatientMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.patient_age != nil {
		fields = append(fields, patient.FieldPatientAge)
	}
	if m.patient_name != nil {
		fields = append(fields, patient.FieldPatientName)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *PatientMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case patient.FieldPatientAge:
		return m.PatientAge()
	case patient.FieldPatientName:
		return m.PatientName()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *PatientMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case patient.FieldPatientAge:
		return m.OldPatientAge(ctx)
	case patient.FieldPatientName:
		return m.OldPatientName(ctx)
	}
	return nil, fmt.Errorf("unknown Patient field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *PatientMutation) SetField(name string, value ent.Value) error {
	switch name {
	case patient.FieldPatientAge:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPatientAge(v)
		return nil
	case patient.FieldPatientName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPatientName(v)
		return nil
	}
	return fmt.Errorf("unknown Patient field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *PatientMutation) AddedFields() []string {
	var fields []string
	if m.addpatient_age != nil {
		fields = append(fields, patient.FieldPatientAge)
	}
	return fields
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *PatientMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case patient.FieldPatientAge:
		return m.AddedPatientAge()
	}
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *PatientMutation) AddField(name string, value ent.Value) error {
	switch name {
	case patient.FieldPatientAge:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPatientAge(v)
		return nil
	}
	return fmt.Errorf("unknown Patient numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *PatientMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *PatientMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *PatientMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Patient nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *PatientMutation) ResetField(name string) error {
	switch name {
	case patient.FieldPatientAge:
		m.ResetPatientAge()
		return nil
	case patient.FieldPatientName:
		m.ResetPatientName()
		return nil
	}
	return fmt.Errorf("unknown Patient field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *PatientMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.patient_id != nil {
		edges = append(edges, patient.EdgePatientID)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *PatientMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case patient.EdgePatientID:
		ids := make([]ent.Value, 0, len(m.patient_id))
		for id := range m.patient_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *PatientMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedpatient_id != nil {
		edges = append(edges, patient.EdgePatientID)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *PatientMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case patient.EdgePatientID:
		ids := make([]ent.Value, 0, len(m.removedpatient_id))
		for id := range m.removedpatient_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *PatientMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *PatientMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *PatientMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Patient unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *PatientMutation) ResetEdge(name string) error {
	switch name {
	case patient.EdgePatientID:
		m.ResetPatientID()
		return nil
	}
	return fmt.Errorf("unknown Patient edge %s", name)
}

// StatusTrackingMutation represents an operation that mutate the StatusTrackings
// nodes in the graph.
type StatusTrackingMutation struct {
	config
	op               Op
	typ              string
	id               *int
	status           *string
	clearedFields    map[string]struct{}
	status_id        map[int]struct{}
	removedstatus_id map[int]struct{}
	done             bool
	oldValue         func(context.Context) (*StatusTracking, error)
}

var _ ent.Mutation = (*StatusTrackingMutation)(nil)

// statustrackingOption allows to manage the mutation configuration using functional options.
type statustrackingOption func(*StatusTrackingMutation)

// newStatusTrackingMutation creates new mutation for $n.Name.
func newStatusTrackingMutation(c config, op Op, opts ...statustrackingOption) *StatusTrackingMutation {
	m := &StatusTrackingMutation{
		config:        c,
		op:            op,
		typ:           TypeStatusTracking,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withStatusTrackingID sets the id field of the mutation.
func withStatusTrackingID(id int) statustrackingOption {
	return func(m *StatusTrackingMutation) {
		var (
			err   error
			once  sync.Once
			value *StatusTracking
		)
		m.oldValue = func(ctx context.Context) (*StatusTracking, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().StatusTracking.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withStatusTracking sets the old StatusTracking of the mutation.
func withStatusTracking(node *StatusTracking) statustrackingOption {
	return func(m *StatusTrackingMutation) {
		m.oldValue = func(context.Context) (*StatusTracking, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m StatusTrackingMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m StatusTrackingMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *StatusTrackingMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetStatus sets the status field.
func (m *StatusTrackingMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the status value in the mutation.
func (m *StatusTrackingMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old status value of the StatusTracking.
// If the StatusTracking object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *StatusTrackingMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldStatus is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus reset all changes of the "status" field.
func (m *StatusTrackingMutation) ResetStatus() {
	m.status = nil
}

// AddStatusIDIDs adds the status_id edge to Treatment by ids.
func (m *StatusTrackingMutation) AddStatusIDIDs(ids ...int) {
	if m.status_id == nil {
		m.status_id = make(map[int]struct{})
	}
	for i := range ids {
		m.status_id[ids[i]] = struct{}{}
	}
}

// RemoveStatusIDIDs removes the status_id edge to Treatment by ids.
func (m *StatusTrackingMutation) RemoveStatusIDIDs(ids ...int) {
	if m.removedstatus_id == nil {
		m.removedstatus_id = make(map[int]struct{})
	}
	for i := range ids {
		m.removedstatus_id[ids[i]] = struct{}{}
	}
}

// RemovedStatusID returns the removed ids of status_id.
func (m *StatusTrackingMutation) RemovedStatusIDIDs() (ids []int) {
	for id := range m.removedstatus_id {
		ids = append(ids, id)
	}
	return
}

// StatusIDIDs returns the status_id ids in the mutation.
func (m *StatusTrackingMutation) StatusIDIDs() (ids []int) {
	for id := range m.status_id {
		ids = append(ids, id)
	}
	return
}

// ResetStatusID reset all changes of the "status_id" edge.
func (m *StatusTrackingMutation) ResetStatusID() {
	m.status_id = nil
	m.removedstatus_id = nil
}

// Op returns the operation name.
func (m *StatusTrackingMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (StatusTracking).
func (m *StatusTrackingMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *StatusTrackingMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.status != nil {
		fields = append(fields, statustracking.FieldStatus)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *StatusTrackingMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case statustracking.FieldStatus:
		return m.Status()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *StatusTrackingMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case statustracking.FieldStatus:
		return m.OldStatus(ctx)
	}
	return nil, fmt.Errorf("unknown StatusTracking field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *StatusTrackingMutation) SetField(name string, value ent.Value) error {
	switch name {
	case statustracking.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	}
	return fmt.Errorf("unknown StatusTracking field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *StatusTrackingMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *StatusTrackingMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *StatusTrackingMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown StatusTracking numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *StatusTrackingMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *StatusTrackingMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *StatusTrackingMutation) ClearField(name string) error {
	return fmt.Errorf("unknown StatusTracking nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *StatusTrackingMutation) ResetField(name string) error {
	switch name {
	case statustracking.FieldStatus:
		m.ResetStatus()
		return nil
	}
	return fmt.Errorf("unknown StatusTracking field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *StatusTrackingMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.status_id != nil {
		edges = append(edges, statustracking.EdgeStatusID)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *StatusTrackingMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case statustracking.EdgeStatusID:
		ids := make([]ent.Value, 0, len(m.status_id))
		for id := range m.status_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *StatusTrackingMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedstatus_id != nil {
		edges = append(edges, statustracking.EdgeStatusID)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *StatusTrackingMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case statustracking.EdgeStatusID:
		ids := make([]ent.Value, 0, len(m.removedstatus_id))
		for id := range m.removedstatus_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *StatusTrackingMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *StatusTrackingMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *StatusTrackingMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown StatusTracking unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *StatusTrackingMutation) ResetEdge(name string) error {
	switch name {
	case statustracking.EdgeStatusID:
		m.ResetStatusID()
		return nil
	}
	return fmt.Errorf("unknown StatusTracking edge %s", name)
}

// TreatmentMutation represents an operation that mutate the Treatments
// nodes in the graph.
type TreatmentMutation struct {
	config
	op                Op
	typ               string
	id                *int
	date_appoint      *time.Time
	symptom           *string
	clearedFields     map[string]struct{}
	patient_id        *int
	clearedpatient_id bool
	doctor_id         *int
	cleareddoctor_id  bool
	status_id         *int
	clearedstatus_id  bool
	done              bool
	oldValue          func(context.Context) (*Treatment, error)
}

var _ ent.Mutation = (*TreatmentMutation)(nil)

// treatmentOption allows to manage the mutation configuration using functional options.
type treatmentOption func(*TreatmentMutation)

// newTreatmentMutation creates new mutation for $n.Name.
func newTreatmentMutation(c config, op Op, opts ...treatmentOption) *TreatmentMutation {
	m := &TreatmentMutation{
		config:        c,
		op:            op,
		typ:           TypeTreatment,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTreatmentID sets the id field of the mutation.
func withTreatmentID(id int) treatmentOption {
	return func(m *TreatmentMutation) {
		var (
			err   error
			once  sync.Once
			value *Treatment
		)
		m.oldValue = func(ctx context.Context) (*Treatment, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Treatment.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTreatment sets the old Treatment of the mutation.
func withTreatment(node *Treatment) treatmentOption {
	return func(m *TreatmentMutation) {
		m.oldValue = func(context.Context) (*Treatment, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TreatmentMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TreatmentMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *TreatmentMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetDateAppoint sets the date_appoint field.
func (m *TreatmentMutation) SetDateAppoint(t time.Time) {
	m.date_appoint = &t
}

// DateAppoint returns the date_appoint value in the mutation.
func (m *TreatmentMutation) DateAppoint() (r time.Time, exists bool) {
	v := m.date_appoint
	if v == nil {
		return
	}
	return *v, true
}

// OldDateAppoint returns the old date_appoint value of the Treatment.
// If the Treatment object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *TreatmentMutation) OldDateAppoint(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldDateAppoint is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldDateAppoint requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDateAppoint: %w", err)
	}
	return oldValue.DateAppoint, nil
}

// ResetDateAppoint reset all changes of the "date_appoint" field.
func (m *TreatmentMutation) ResetDateAppoint() {
	m.date_appoint = nil
}

// SetSymptom sets the symptom field.
func (m *TreatmentMutation) SetSymptom(s string) {
	m.symptom = &s
}

// Symptom returns the symptom value in the mutation.
func (m *TreatmentMutation) Symptom() (r string, exists bool) {
	v := m.symptom
	if v == nil {
		return
	}
	return *v, true
}

// OldSymptom returns the old symptom value of the Treatment.
// If the Treatment object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *TreatmentMutation) OldSymptom(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldSymptom is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldSymptom requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSymptom: %w", err)
	}
	return oldValue.Symptom, nil
}

// ResetSymptom reset all changes of the "symptom" field.
func (m *TreatmentMutation) ResetSymptom() {
	m.symptom = nil
}

// SetPatientIDID sets the patient_id edge to Patient by id.
func (m *TreatmentMutation) SetPatientIDID(id int) {
	m.patient_id = &id
}

// ClearPatientID clears the patient_id edge to Patient.
func (m *TreatmentMutation) ClearPatientID() {
	m.clearedpatient_id = true
}

// PatientIDCleared returns if the edge patient_id was cleared.
func (m *TreatmentMutation) PatientIDCleared() bool {
	return m.clearedpatient_id
}

// PatientIDID returns the patient_id id in the mutation.
func (m *TreatmentMutation) PatientIDID() (id int, exists bool) {
	if m.patient_id != nil {
		return *m.patient_id, true
	}
	return
}

// PatientIDIDs returns the patient_id ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// PatientIDID instead. It exists only for internal usage by the builders.
func (m *TreatmentMutation) PatientIDIDs() (ids []int) {
	if id := m.patient_id; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetPatientID reset all changes of the "patient_id" edge.
func (m *TreatmentMutation) ResetPatientID() {
	m.patient_id = nil
	m.clearedpatient_id = false
}

// SetDoctorIDID sets the doctor_id edge to User by id.
func (m *TreatmentMutation) SetDoctorIDID(id int) {
	m.doctor_id = &id
}

// ClearDoctorID clears the doctor_id edge to User.
func (m *TreatmentMutation) ClearDoctorID() {
	m.cleareddoctor_id = true
}

// DoctorIDCleared returns if the edge doctor_id was cleared.
func (m *TreatmentMutation) DoctorIDCleared() bool {
	return m.cleareddoctor_id
}

// DoctorIDID returns the doctor_id id in the mutation.
func (m *TreatmentMutation) DoctorIDID() (id int, exists bool) {
	if m.doctor_id != nil {
		return *m.doctor_id, true
	}
	return
}

// DoctorIDIDs returns the doctor_id ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// DoctorIDID instead. It exists only for internal usage by the builders.
func (m *TreatmentMutation) DoctorIDIDs() (ids []int) {
	if id := m.doctor_id; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetDoctorID reset all changes of the "doctor_id" edge.
func (m *TreatmentMutation) ResetDoctorID() {
	m.doctor_id = nil
	m.cleareddoctor_id = false
}

// SetStatusIDID sets the status_id edge to StatusTracking by id.
func (m *TreatmentMutation) SetStatusIDID(id int) {
	m.status_id = &id
}

// ClearStatusID clears the status_id edge to StatusTracking.
func (m *TreatmentMutation) ClearStatusID() {
	m.clearedstatus_id = true
}

// StatusIDCleared returns if the edge status_id was cleared.
func (m *TreatmentMutation) StatusIDCleared() bool {
	return m.clearedstatus_id
}

// StatusIDID returns the status_id id in the mutation.
func (m *TreatmentMutation) StatusIDID() (id int, exists bool) {
	if m.status_id != nil {
		return *m.status_id, true
	}
	return
}

// StatusIDIDs returns the status_id ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// StatusIDID instead. It exists only for internal usage by the builders.
func (m *TreatmentMutation) StatusIDIDs() (ids []int) {
	if id := m.status_id; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetStatusID reset all changes of the "status_id" edge.
func (m *TreatmentMutation) ResetStatusID() {
	m.status_id = nil
	m.clearedstatus_id = false
}

// Op returns the operation name.
func (m *TreatmentMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Treatment).
func (m *TreatmentMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *TreatmentMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.date_appoint != nil {
		fields = append(fields, treatment.FieldDateAppoint)
	}
	if m.symptom != nil {
		fields = append(fields, treatment.FieldSymptom)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *TreatmentMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case treatment.FieldDateAppoint:
		return m.DateAppoint()
	case treatment.FieldSymptom:
		return m.Symptom()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *TreatmentMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case treatment.FieldDateAppoint:
		return m.OldDateAppoint(ctx)
	case treatment.FieldSymptom:
		return m.OldSymptom(ctx)
	}
	return nil, fmt.Errorf("unknown Treatment field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *TreatmentMutation) SetField(name string, value ent.Value) error {
	switch name {
	case treatment.FieldDateAppoint:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateAppoint(v)
		return nil
	case treatment.FieldSymptom:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSymptom(v)
		return nil
	}
	return fmt.Errorf("unknown Treatment field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *TreatmentMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *TreatmentMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *TreatmentMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Treatment numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *TreatmentMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *TreatmentMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *TreatmentMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Treatment nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *TreatmentMutation) ResetField(name string) error {
	switch name {
	case treatment.FieldDateAppoint:
		m.ResetDateAppoint()
		return nil
	case treatment.FieldSymptom:
		m.ResetSymptom()
		return nil
	}
	return fmt.Errorf("unknown Treatment field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *TreatmentMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.patient_id != nil {
		edges = append(edges, treatment.EdgePatientID)
	}
	if m.doctor_id != nil {
		edges = append(edges, treatment.EdgeDoctorID)
	}
	if m.status_id != nil {
		edges = append(edges, treatment.EdgeStatusID)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *TreatmentMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case treatment.EdgePatientID:
		if id := m.patient_id; id != nil {
			return []ent.Value{*id}
		}
	case treatment.EdgeDoctorID:
		if id := m.doctor_id; id != nil {
			return []ent.Value{*id}
		}
	case treatment.EdgeStatusID:
		if id := m.status_id; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *TreatmentMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *TreatmentMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *TreatmentMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	if m.clearedpatient_id {
		edges = append(edges, treatment.EdgePatientID)
	}
	if m.cleareddoctor_id {
		edges = append(edges, treatment.EdgeDoctorID)
	}
	if m.clearedstatus_id {
		edges = append(edges, treatment.EdgeStatusID)
	}
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *TreatmentMutation) EdgeCleared(name string) bool {
	switch name {
	case treatment.EdgePatientID:
		return m.clearedpatient_id
	case treatment.EdgeDoctorID:
		return m.cleareddoctor_id
	case treatment.EdgeStatusID:
		return m.clearedstatus_id
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *TreatmentMutation) ClearEdge(name string) error {
	switch name {
	case treatment.EdgePatientID:
		m.ClearPatientID()
		return nil
	case treatment.EdgeDoctorID:
		m.ClearDoctorID()
		return nil
	case treatment.EdgeStatusID:
		m.ClearStatusID()
		return nil
	}
	return fmt.Errorf("unknown Treatment unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *TreatmentMutation) ResetEdge(name string) error {
	switch name {
	case treatment.EdgePatientID:
		m.ResetPatientID()
		return nil
	case treatment.EdgeDoctorID:
		m.ResetDoctorID()
		return nil
	case treatment.EdgeStatusID:
		m.ResetStatusID()
		return nil
	}
	return fmt.Errorf("unknown Treatment edge %s", name)
}

// UserMutation represents an operation that mutate the Users
// nodes in the graph.
type UserMutation struct {
	config
	op               Op
	typ              string
	id               *int
	doctor_email     *string
	doctor_name      *string
	clearedFields    map[string]struct{}
	doctor_id        map[int]struct{}
	removeddoctor_id map[int]struct{}
	done             bool
	oldValue         func(context.Context) (*User, error)
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows to manage the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for $n.Name.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the id field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetDoctorEmail sets the doctor_email field.
func (m *UserMutation) SetDoctorEmail(s string) {
	m.doctor_email = &s
}

// DoctorEmail returns the doctor_email value in the mutation.
func (m *UserMutation) DoctorEmail() (r string, exists bool) {
	v := m.doctor_email
	if v == nil {
		return
	}
	return *v, true
}

// OldDoctorEmail returns the old doctor_email value of the User.
// If the User object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *UserMutation) OldDoctorEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldDoctorEmail is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldDoctorEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDoctorEmail: %w", err)
	}
	return oldValue.DoctorEmail, nil
}

// ResetDoctorEmail reset all changes of the "doctor_email" field.
func (m *UserMutation) ResetDoctorEmail() {
	m.doctor_email = nil
}

// SetDoctorName sets the doctor_name field.
func (m *UserMutation) SetDoctorName(s string) {
	m.doctor_name = &s
}

// DoctorName returns the doctor_name value in the mutation.
func (m *UserMutation) DoctorName() (r string, exists bool) {
	v := m.doctor_name
	if v == nil {
		return
	}
	return *v, true
}

// OldDoctorName returns the old doctor_name value of the User.
// If the User object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *UserMutation) OldDoctorName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldDoctorName is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldDoctorName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDoctorName: %w", err)
	}
	return oldValue.DoctorName, nil
}

// ResetDoctorName reset all changes of the "doctor_name" field.
func (m *UserMutation) ResetDoctorName() {
	m.doctor_name = nil
}

// AddDoctorIDIDs adds the doctor_id edge to Treatment by ids.
func (m *UserMutation) AddDoctorIDIDs(ids ...int) {
	if m.doctor_id == nil {
		m.doctor_id = make(map[int]struct{})
	}
	for i := range ids {
		m.doctor_id[ids[i]] = struct{}{}
	}
}

// RemoveDoctorIDIDs removes the doctor_id edge to Treatment by ids.
func (m *UserMutation) RemoveDoctorIDIDs(ids ...int) {
	if m.removeddoctor_id == nil {
		m.removeddoctor_id = make(map[int]struct{})
	}
	for i := range ids {
		m.removeddoctor_id[ids[i]] = struct{}{}
	}
}

// RemovedDoctorID returns the removed ids of doctor_id.
func (m *UserMutation) RemovedDoctorIDIDs() (ids []int) {
	for id := range m.removeddoctor_id {
		ids = append(ids, id)
	}
	return
}

// DoctorIDIDs returns the doctor_id ids in the mutation.
func (m *UserMutation) DoctorIDIDs() (ids []int) {
	for id := range m.doctor_id {
		ids = append(ids, id)
	}
	return
}

// ResetDoctorID reset all changes of the "doctor_id" edge.
func (m *UserMutation) ResetDoctorID() {
	m.doctor_id = nil
	m.removeddoctor_id = nil
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.doctor_email != nil {
		fields = append(fields, user.FieldDoctorEmail)
	}
	if m.doctor_name != nil {
		fields = append(fields, user.FieldDoctorName)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldDoctorEmail:
		return m.DoctorEmail()
	case user.FieldDoctorName:
		return m.DoctorName()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldDoctorEmail:
		return m.OldDoctorEmail(ctx)
	case user.FieldDoctorName:
		return m.OldDoctorName(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldDoctorEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDoctorEmail(v)
		return nil
	case user.FieldDoctorName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDoctorName(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldDoctorEmail:
		m.ResetDoctorEmail()
		return nil
	case user.FieldDoctorName:
		m.ResetDoctorName()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.doctor_id != nil {
		edges = append(edges, user.EdgeDoctorID)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeDoctorID:
		ids := make([]ent.Value, 0, len(m.doctor_id))
		for id := range m.doctor_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removeddoctor_id != nil {
		edges = append(edges, user.EdgeDoctorID)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeDoctorID:
		ids := make([]ent.Value, 0, len(m.removeddoctor_id))
		for id := range m.removeddoctor_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeDoctorID:
		m.ResetDoctorID()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
