// Code generated by entc, DO NOT EDIT.

package treatment

import (
	"time"
)

const (
	// Label holds the string label denoting the treatment type in the database.
	Label = "treatment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDateAppoint holds the string denoting the date_appoint field in the database.
	FieldDateAppoint = "date_appoint"
	// FieldSymptom holds the string denoting the symptom field in the database.
	FieldSymptom = "symptom"

	// EdgePatientID holds the string denoting the patient_id edge name in mutations.
	EdgePatientID = "patient_id"
	// EdgeDoctorID holds the string denoting the doctor_id edge name in mutations.
	EdgeDoctorID = "doctor_id"
	// EdgeStatusID holds the string denoting the status_id edge name in mutations.
	EdgeStatusID = "status_id"

	// Table holds the table name of the treatment in the database.
	Table = "treatments"
	// PatientIDTable is the table the holds the patient_id relation/edge.
	PatientIDTable = "treatments"
	// PatientIDInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientIDInverseTable = "patients"
	// PatientIDColumn is the table column denoting the patient_id relation/edge.
	PatientIDColumn = "patient_patient_id"
	// DoctorIDTable is the table the holds the doctor_id relation/edge.
	DoctorIDTable = "treatments"
	// DoctorIDInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	DoctorIDInverseTable = "users"
	// DoctorIDColumn is the table column denoting the doctor_id relation/edge.
	DoctorIDColumn = "user_doctor_id"
	// StatusIDTable is the table the holds the status_id relation/edge.
	StatusIDTable = "treatments"
	// StatusIDInverseTable is the table name for the StatusTracking entity.
	// It exists in this package in order to avoid circular dependency with the "statustracking" package.
	StatusIDInverseTable = "status_trackings"
	// StatusIDColumn is the table column denoting the status_id relation/edge.
	StatusIDColumn = "status_tracking_status_id"
)

// Columns holds all SQL columns for treatment fields.
var Columns = []string{
	FieldID,
	FieldDateAppoint,
	FieldSymptom,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Treatment type.
var ForeignKeys = []string{
	"patient_patient_id",
	"status_tracking_status_id",
	"user_doctor_id",
}

var (
	// DefaultDateAppoint holds the default value on creation for the date_appoint field.
	DefaultDateAppoint func() time.Time
)
