// Code generated by entc, DO NOT EDIT.

package statustracking

const (
	// Label holds the string label denoting the statustracking type in the database.
	Label = "status_tracking"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"

	// EdgeStatusID holds the string denoting the status_id edge name in mutations.
	EdgeStatusID = "status_id"

	// Table holds the table name of the statustracking in the database.
	Table = "status_trackings"
	// StatusIDTable is the table the holds the status_id relation/edge.
	StatusIDTable = "treatments"
	// StatusIDInverseTable is the table name for the Treatment entity.
	// It exists in this package in order to avoid circular dependency with the "treatment" package.
	StatusIDInverseTable = "treatments"
	// StatusIDColumn is the table column denoting the status_id relation/edge.
	StatusIDColumn = "status_tracking_status_id"
)

// Columns holds all SQL columns for statustracking fields.
var Columns = []string{
	FieldID,
	FieldStatus,
}

var (
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
)
