/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntTreatment,
    EntTreatmentFromJSON,
    EntTreatmentFromJSONTyped,
    EntTreatmentToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntStatusTrackingEdges
 */
export interface EntStatusTrackingEdges {
    /**
     * StatusID holds the value of the status_id edge.
     * @type {Array<EntTreatment>}
     * @memberof EntStatusTrackingEdges
     */
    statusID?: Array<EntTreatment>;
}

export function EntStatusTrackingEdgesFromJSON(json: any): EntStatusTrackingEdges {
    return EntStatusTrackingEdgesFromJSONTyped(json, false);
}

export function EntStatusTrackingEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntStatusTrackingEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusID': !exists(json, 'statusID') ? undefined : ((json['statusID'] as Array<any>).map(EntTreatmentFromJSON)),
    };
}

export function EntStatusTrackingEdgesToJSON(value?: EntStatusTrackingEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statusID': value.statusID === undefined ? undefined : ((value.statusID as Array<any>).map(EntTreatmentToJSON)),
    };
}


