/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntTreatmentEdges,
    EntTreatmentEdgesFromJSON,
    EntTreatmentEdgesFromJSONTyped,
    EntTreatmentEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntTreatment
 */
export interface EntTreatment {
    /**
     * DateAppoint holds the value of the "date_appoint" field.
     * @type {string}
     * @memberof EntTreatment
     */
    dateAppoint?: string;
    /**
     * 
     * @type {EntTreatmentEdges}
     * @memberof EntTreatment
     */
    edges?: EntTreatmentEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntTreatment
     */
    id?: number;
    /**
     * Symptom holds the value of the "symptom" field.
     * @type {string}
     * @memberof EntTreatment
     */
    symptom?: string;
}

export function EntTreatmentFromJSON(json: any): EntTreatment {
    return EntTreatmentFromJSONTyped(json, false);
}

export function EntTreatmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntTreatment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dateAppoint': !exists(json, 'date_appoint') ? undefined : json['date_appoint'],
        'edges': !exists(json, 'edges') ? undefined : EntTreatmentEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'symptom': !exists(json, 'symptom') ? undefined : json['symptom'],
    };
}

export function EntTreatmentToJSON(value?: EntTreatment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date_appoint': value.dateAppoint,
        'edges': EntTreatmentEdgesToJSON(value.edges),
        'id': value.id,
        'symptom': value.symptom,
    };
}


